db_tier: db-f1-micro
db_version: POSTGRES_14
minReplicas: 1
maxReplicas: 1
kafkaPool: nav-dev
cpu: 200m
memory: 400Mi
env:
  SPINNSYN_FRONTEND_URL: 'https://www.ekstern.dev.nav.no/syk/sykepenger'
  SPRING_PROFILES_ACTIVE: default,testdatareset
