db_tier: db-f1-micro
minReplicas: '1'
maxReplicas: '2'
kafkaPool: nav-dev
cpu: 200m
memory: 400Mi
externalHosts:
  - kafka-schema-registry.nais-q.adeo.no
env:
  SPINNSYN_FRONTEND_URL: 'https://www.ekstern.dev.nav.no/syk/sykepenger'
  SPRING_PROFILES_ACTIVE: default,testdatareset
