apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-brukernotifikasjon
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
    initialDelay: 60
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 400m
      memory: 650Mi
    requests:
      cpu: 200m
      memory: 400Mi
  gcp:
    sqlInstances:
      - name: spinnsyn-brukernotifikasjon-sqlinstance
        type: POSTGRES_12
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: spinnsyn-brukernotifikasjon-db
            envVarPrefix: DB
  accessPolicy:
    outbound:
      external:
      {{#each externalHosts as |url|}}
         - host: {{url}}
      {{/each}}
  kafka:
    pool: {{kafkaPool}}
  leaderElection: true
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
