apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinnsyn-brukernotifikasjon
  namespace: flex
  labels:
    team: flex
spec:
  image: {{image}}
  strategy:
    type: Recreate
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  gcp:
    sqlInstances:
      - name: spinnsyn-brukernotifikasjon-sqlinstance
        type: {{db_version}}
        tier: {{db_tier}}
        diskAutoresize: true
        databases:
          - name: spinnsyn-brukernotifikasjon-db
            envVarPrefix: DB
  kafka:
    pool: {{kafkaPool}}
  leaderElection: true
  env:
  {{#each env}}
     - name: {{@key}}
       value: {{this}}
  {{/each}}
