db_tier: db-custom-1-3840
db_version: POSTGRES_12
minReplicas: 0
maxReplicas: 0
kafkaPool: nav-prod
cpu: 200m
memory: 600Mi
env:
  SPINNSYN_FRONTEND_URL: 'https://www.nav.no/syk/sykepenger'
  SPRING_PROFILES_ACTIVE: default
