db_tier: db-custom-1-3840
minReplicas: '1'
maxReplicas: '2'
kafkaPool: nav-prod
externalHosts:
  - kafka-schema-registry.nais.adeo.no
env:
  SPINNSYN_FRONTEND_URL: 'https://www.nav.no/syk/sykepenger'
  SPRING_PROFILES_ACTIVE: default
