db_tier: db-custom-1-3840
db_version: POSTGRES_14
minReplicas: 1
maxReplicas: 2
kafkaPool: nav-prod
cpu: 50m
memory: 512Mi
env:
  SPINNSYN_FRONTEND_URL: 'https://www.nav.no/syk/sykepenger'
  SPRING_PROFILES_ACTIVE: default
