server:
  port: 8080

spring:
  main.banner-mode: 'off'
  profiles:
    active: default
  flyway:
    enabled: true
  datasource:
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3

aiven-kafka:
  auto-offset-reset: none
  security-protocol: SSL

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: health,prometheus

logging.config: "classpath:logback.xml"

nais.cluster: ${NAIS_CLUSTER_NAME}
spinnsyn-frontend.url: ${SPINNSYN_FRONTEND_URL}
